apiVersion: v1
kind: ReplicationController
metadata:
  name: heapster-v1.0.0
  namespace: kube-system
  labels:
    k8s-app: heapster
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: heapster
  template:
    metadata:
      labels:
        k8s-app: heapster
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: gcr.io/google_containers/heapster:v1.0.0
          name: heapster
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
          command:
            - /heapster
            - --source=kubernetes:''
            - --sink=influxdb:http://monitoring-influxdb:8086
            - --stats_resolution=10s
            - --sink_frequency=10s
